### ISSUE TITLE
时间选择器添加固定时间范围

### ISSUE THREAD

**Issue by muchenfine** [tusen-ai/naive-ui#3533] opened 2022-08-17 07:41 UTC
### This function solves the problem (这个功能解决的问题)
如果先选中了开始（或结束）时间，则结束（或开始）时间的状态也将会随之改变。
### Expected API (期望的 API)
如果先选中了开始（或结束）时间，则结束（或开始）时间的状态也将会随之改变。

https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby10aW1lLXJhbmdlXCI+XG4gICAgPGVsLXRpbWUtc2VsZWN0XG4gICAgICB2LW1vZGVsPVwic3RhcnRUaW1lXCJcbiAgICAgIDptYXgtdGltZT1cImVuZFRpbWVcIlxuICAgICAgY2xhc3M9XCJtci00XCJcbiAgICAgIHBsYWNlaG9sZGVyPVwiU3RhcnQgdGltZVwiXG4gICAgICBzdGFydD1cIjA4OjMwXCJcbiAgICAgIHN0ZXA9XCIwMDoxNVwiXG4gICAgICBlbmQ9XCIxODozMFwiXG4gICAgLz5cbiAgICA8ZWwtdGltZS1zZWxlY3RcbiAgICAgIHYtbW9kZWw9XCJlbmRUaW1lXCJcbiAgICAgIDptaW4tdGltZT1cInN0YXJ0VGltZVwiXG4gICAgICBwbGFjZWhvbGRlcj1cIkVuZCB0aW1lXCJcbiAgICAgIHN0YXJ0PVwiMDg6MzBcIlxuICAgICAgc3RlcD1cIjAwOjE1XCJcbiAgICAgIGVuZD1cIjE4OjMwXCJcbiAgICAvPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHN0YXJ0VGltZSA9IHJlZignJylcbmNvbnN0IGVuZFRpbWUgPSByZWYoJycpXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==

**Comment by equt** [comment] 2022-08-19 07:56
duplicate of https://github.com/tusen-ai/naive-ui/issues/390

**Closed by equt** 2022-08-19 07:57 UTC
Labels: feature request
