### ISSUE TITLE
使用update:formatted-value后·选择日期后数据消息

### ISSUE THREAD

**Issue by yudan215** [tusen-ai/naive-ui#4766] opened 2023-04-25 03:29 UTC
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-beta.1

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://github.com/看下面地址

### Reappearance steps (重现步骤)
使用update:formatted-value后·选择日期后数据消失
演示地址：https://1024code.com/codecubes/zqsmi6w

### Expected results (期望的结果)
正常显示

### Actual results (实际的结果)
使用update:formatted-value后·选择日期后数据消息

**Comment by amadeus711** [comment] 2023-05-09 02:08
![image](https://user-images.githubusercontent.com/46394163/236975993-378d088a-3a2b-44db-b0c9-5865e46709ad.png)
链接打开无复现

**Comment by yudan215** [comment] 2023-05-10 01:25
> ![image](https://user-images.githubusercontent.com/46394163/236975993-378d088a-3a2b-44db-b0c9-5865e46709ad.png) 链接打开无复现

早上我用Edge也出现这个问题，多刷新几次就可以了·建议使用谷歌浏览器

**Comment by jizai1125** [comment] 2023-05-10 05:16
Upgrade the Vue version to 3.2.46 or higher to fix this issue. It's caused by Vue compiler treating `v-model:kebab-case` and `@update:kebab-case` inconsistently, which has been fixed in Vue [3.2.46](https://github.com/vuejs/core/issues/7067). 
Before the fix, `v-model:kebab-case` would compile to `onUpdate:kebab-case`, and `@update:kebab-case` would compile to `onUpdate:kebabCase`. Now, they will all compile to `onUpdate:kebabCase`.

**Comment by yudan215** [comment] 2023-05-10 08:42
> Upgrade the Vue version to 3.2.46 or higher to fix this issue. It's caused by Vue compiler treating `v-model:kebab-case` and `@update:kebab-case` inconsistently, which has been fixed in Vue [3.2.46.](https://github.com/vuejs/core/issues/7067). Before the fix, `v-model:kebab-case` would compile to `onUpdate:kebab-case`, and `@update:kebab-case` would compile to `onUpdate:kebabCase`. Now, they will all compile to `onUpdate:kebabCase`.
> 
> Alternatively, you can use camelCase instead of kebab-case, like this:
> 
> ```
> <n-date-picker
>     v-model:formattedValue="monthRange"
>     @update:formattedValue="handleMonthRange"
>  />
> ```

升级3.2.46，导致项目起不来了，compileTemplate is not a function

**Closed** 2023-05-19 01:30 UTC
Labels: need reproduction, needs-more-info
