### ISSUE TITLE
Add scrollbar's `trigger` prop to data-table

### ISSUE THREAD

**Issue by benruehl** [tusen-ai/naive-ui#3394] opened 2022-07-29 11:38 UTC
### This function solves the problem (这个功能解决的问题)
We would like to display the data-table's scrollbars all the time.

Currently, the scrollbars fade in when the cursor enters the component and fade out when it leaves.
The scrollbar component already offers a `trigger` property that can be used for this but it is not available on the data-table component to control its built-in scrollbar.

I'd like to suggest that the `trigger` property is added to the data-table and passed down to its child scrollbar.

Thank you for building this awesome library!
### Expected API (期望的 API)
```html
<NDataTable :scroll-trigger="'hover' | 'none'" />
```

**Comment by equt** [comment] 2022-08-18 11:03
seems to be a duplicate of #1573

**Closed by equt** 2022-08-18 11:03 UTC
Labels: feature request
