### ISSUE TITLE
Replace the three dots '...' in the ellipsis component with a custom text/icon like '...read more'

### ISSUE THREAD

**Issue by amkhrjee** [tusen-ai/naive-ui#2553] opened 2022-03-04 12:14 UTC
### This function solves the problem (这个功能解决的问题)
It makes it more clear to the user that there is more text to read with a '...read more' text and/or an icon with a different color than the rest of the text. Plus, it gives a broader area to tap/click on. 
### Expected API (期望的 API)
```html 

<n-ellipsis>
...
content
...
 <template color="blue" #custom>
   ...read more
    <Icon>
        <SomeIcon/>
    </Icon>
 </template>
</n-ellipsis>
```

**Comment by 07akioni** [comment] 2022-03-05 17:47
This would be a very complex feature. Also it's hard to implement it in a robust way.

I won't add the feature, but PR is welcomed.

**Comment by 07akioni** [comment] 2022-03-05 17:48
This is a good case.

https://www.npmjs.com/package/react-ellipsis-component

**Comment by equt** [comment] 2022-08-20 03:15
duplicate of https://github.com/tusen-ai/naive-ui/issues/75

**Closed by equt** 2022-08-20 03:15 UTC
Labels: feature request, pr welcome
