### ISSUE TITLE
数字控件双击后数字会一直增加，无法停止

### ISSUE THREAD

**Issue by fanmore** [tusen-ai/naive-ui#3486] opened 2022-08-11 06:32 UTC
### TuSimple/naive-ui version (版本)
2.32.2-beta.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
windows10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/input-number

### Reappearance steps (重现步骤)
https://s3.bmp.ovh/imgs/2022/08/11/8815a173de34f344.gif

### Expected results (期望的结果)
不应该一直增加才对

### Actual results (实际的结果)
数字输入 Input Number 双击增加位置，数字会一直增加，无法停止

**Comment by ManiaJack** [comment] 2022-08-11 09:18
我在自己的代码里面 2.32.1 也碰到了这个问题，双击减号也会触发。但是在文档上我却复现不出来。感觉像是按住的事件被一直触发了.

**Comment by OrbisK** [comment] 2022-08-11 09:44
this might be a duplicate of #3329

**Comment by Sepush** [comment] 2022-08-11 12:52
can't reproduce it
无法复现
https://user-images.githubusercontent.com/39197136/184137357-de3d0d29-abed-4598-aacf-58a47b424d95.mp4

**Comment by OrbisK** [comment] 2022-08-11 12:57
> can't reproduce it 无法复现 https://user-images.githubusercontent.com/39197136/184137357-de3d0d29-abed-4598-aacf-58a47b424d95.mp4

you have to click pretty fast. https://github.com/tusen-ai/naive-ui/issues/3329#issuecomment-1198350120

**Comment by 07akioni** [comment] 2022-08-11 17:28
Seem to be a tricky bug. We will try to fix it soon.

**Comment by 07akioni** [comment] 2022-08-12 15:20
duplicate, track it in https://github.com/tusen-ai/naive-ui/issues/3329

**Closed by 07akioni** 2022-08-12 15:20 UTC
Labels: bug, priority: high
